package server;

import client.MapleCharacter;
import handling.world.MapleParty;
import handling.world.MaplePartyCharacter;
import java.lang.ref.WeakReference;
import server.maps.MapleMap;

public class MapleCarnivalChallenge {

    WeakReference<MapleCharacter> challenger;
    String challengeinfo = "";

    public MapleCarnivalChallenge(MapleCharacter challenger) {
        this.challenger = new WeakReference(challenger);
        this.challengeinfo += "#b";
        for (MaplePartyCharacter pc : challenger.getParty().getMembers()) {
            MapleCharacter c = challenger.getMap().getCharacterById(pc.getId());
            if (c != null) {
                this.challengeinfo = (this.challengeinfo + c.getName() + " / Level" + c.getLevel() + " / " + getJobNameById(c.getJob()));
            }
        }
        this.challengeinfo += "#k";
    }

    public MapleCharacter getChallenger() {
        return (MapleCharacter) this.challenger.get();
    }

    public String getChallengeInfo() {
        return this.challengeinfo;
    }

    public static String getJobNameById(int job) {
        switch (job) {
            case 0:
            case 1:
                return "新手";
            case 1000:
                return "初心者";
            case 2000:
                return "战童";
            case 2001:
                return "小不点";
            case 3000:
                return "预备兵";
            case 100:
                return "战士";
            case 110:
                return "剑客";
            case 111:
                return "勇士";
            case 112:
                return "英雄";
            case 120:
                return "准骑士";
            case 121:
                return "骑士";
            case 122:
                return "圣骑士";
            case 130:
                return "枪战士";
            case 131:
                return "龙骑士";
            case 132:
                return "黑骑士";
            case 200:
                return "魔法师";
            case 210:
                return "火毒法师";
            case 211:
                return "火毒巫师";
            case 212:
                return "火毒魔导师";
            case 220:
                return "冰雷法师";
            case 221:
                return "冰雷巫师";
            case 222:
                return "冰雷魔导师";
            case 230:
                return "牧师";
            case 231:
                return "祭祀";
            case 232:
                return "主教";
            case 300:
                return "弓箭手";
            case 310:
                return "猎人";
            case 311:
                return "射手";
            case 312:
                return "神射手";
            case 320:
                return "弩弓手";
            case 321:
                return "游侠";
            case 322:
                return "箭神";
            case 400:
                return "飞侠";
            case 410:
                return "刺客";
            case 411:
                return "无影人";
            case 412:
                return "隐士";
            case 420:
                return "侠客";
            case 421:
                return "独行客";
            case 422:
                return "侠盗";
            case 430:
                return "见习刀客";
            case 431:
                return "双刀客";
            case 432:
                return "双刀侠";
            case 433:
                return "血刀";
            case 434:
                return "暗影双刀";
            case 500:
                return "海盗(作废)";
            case 510:
                return "拳手(作废)";
            case 511:
                return "斗士(作废)";
            case 512:
                return "冲锋队长(作废)";
            case 520:
                return "火枪手(作废)";
            case 521:
                return "大副(作废)";
            case 522:
                return "船长(作废)";
            case 501:
                return "海盗炮手";
            case 530:
                return "火炮手";
            case 531:
                return "毁灭炮手";
            case 532:
                return "神炮王";
            case 508:
            case 570:
            case 571:
            case 572:
                return "龙的传人";
            case 509:
                return "海盗(新)";
            case 580:
                return "拳手(新)";
            case 581:
                return "斗士(新)";
            case 582:
                return "冲锋队长(新)";
            case 590:
                return "火枪手(新)";
            case 591:
                return "大副(新)";
            case 592:
                return "船长(新)";
            case 1100:
            case 1110:
            case 1111:
            case 1112:
                return "魂骑士";
            case 1200:
            case 1210:
            case 1211:
            case 1212:
                return "炎术士";
            case 1300:
            case 1310:
            case 1311:
            case 1312:
                return "风灵使者";
            case 1400:
            case 1410:
            case 1411:
            case 1412:
                return "夜行者";
            case 1500:
            case 1510:
            case 1511:
            case 1512:
                return "奇袭者";
            case 2100:
            case 2110:
            case 2111:
            case 2112:
                return "战神";
            case 2200:
            case 2210:
            case 2211:
            case 2212:
            case 2213:
            case 2214:
            case 2215:
            case 2216:
            case 2217:
            case 2218:
                return "龙神";
            case 2002:
            case 2300:
            case 2310:
            case 2311:
            case 2312:
                return "双弩精灵";
            case 2003:
            case 2400:
            case 2410:
            case 2411:
            case 2412:
                return "幻影";
                
                    case 2004:
    case 2700:
    case 2710:
    case 2711:
    case 2712:
      return "夜光";
                
                
            case 3001:
            case 3100:
            case 3110:
            case 3111:
            case 3112:
                return "恶魔猎手";
            case 3200:
            case 3210:
            case 3211:
            case 3212:
                return "幻灵斗师";
            case 3300:
            case 3310:
            case 3311:
            case 3312:
                return "弩豹游侠";
            case 3500:
            case 3510:
            case 3511:
            case 3512:
                return "机械师";
            case 5000:
            case 5100:
            case 5110:
            case 5111:
            case 5112:
                return "米哈尔";
                
                
    case 6000:
    case 6100:
    case 6110:
    case 6111:
    case 6112:
      return "狂龙战士";
    case 6001:
    case 6500:
    case 6510:
    case 6511:
    case 6512:
      return "爆莉萌天使";
                
                
            case 900:
                return "管理员";
            case 910:
                return "超级管理员";
            case 800:
                return "管理者";
        }
        return "";
    }

    public static String getJobBasicNameById(int job) {
        switch (job) {
            case 0:
            case 1:
            case 1000:
            case 2000:
            case 2001:
            case 2002:
            case 3000:
            case 3001:
            case 5000:
                return "Beginner";
            case 100:
            case 110:
            case 111:
            case 112:
            case 120:
            case 121:
            case 122:
            case 130:
            case 131:
            case 132:
            case 1100:
            case 1110:
            case 1111:
            case 1112:
            case 2100:
            case 2110:
            case 2111:
            case 2112:
            case 3100:
            case 3110:
            case 3111:
            case 3112:
        //    case 5100:
          //  case 5110:
           // case 5111:
          //  case 5112:
                return "Warrior";
            case 200:
            case 210:
            case 211:
            case 212:
            case 220:
            case 221:
            case 222:
            case 230:
            case 231:
            case 232:
            case 1200:
            case 1210:
            case 1211:
            case 1212:
            case 2200:
            case 2210:
            case 2211:
            case 2212:
            case 2213:
            case 2214:
            case 2215:
            case 2216:
            case 2217:
            case 2218:
            case 3200:
            case 3210:
            case 3211:
            case 3212:
                return "Magician";
            case 300:
            case 310:
            case 311:
            case 312:
            case 320:
            case 321:
            case 322:
            case 1300:
            case 1310:
            case 1311:
            case 1312:
            case 2300:
            case 2310:
            case 2311:
            case 2312:
            case 3300:
            case 3310:
            case 3311:
            case 3312:
                return "Bowman";
            case 400:
            case 410:
            case 411:
            case 412:
            case 420:
            case 421:
            case 422:
            case 430:
            case 431:
            case 432:
            case 433:
            case 434:
            case 1400:
            case 1410:
            case 1411:
            case 1412:
                return "Thief";
            case 500:
            case 501:
            case 508:
            case 509:
            case 510:
            case 511:
            case 512:
            case 520:
            case 521:
            case 522:
            case 530:
            case 531:
            case 532:
            case 570:
            case 571:
            case 572:
            case 580:
            case 581:
            case 582:
            case 590:
            case 591:
            case 592:
            case 1500:
            case 1510:
            case 1511:
            case 1512:
            case 3500:
            case 3510:
            case 3511:
            case 3512:
                return "Pirate";
        }
        return "";
    }

    public static String getJobNameByIdNull(int job) {
        switch (job) {
            case 0:
            case 1:
                return "新手";
            case 1000:
                return "初心者";
            case 2000:
                return "战童";
            case 2001:
                return "小不点";
            case 3000:
                return "预备兵";
            case 100:
                return "战士";
            case 110:
                return "剑客";
            case 111:
                return "勇士";
            case 112:
                return "英雄";
            case 120:
                return "准骑士";
            case 121:
                return "骑士";
            case 122:
                return "圣骑士";
            case 130:
                return "枪战士";
            case 131:
                return "龙骑士";
            case 132:
                return "黑骑士";
            case 200:
                return "魔法师";
            case 210:
                return "火毒法师";
            case 211:
                return "火毒巫师";
            case 212:
                return "火毒魔导师";
            case 220:
                return "冰雷法师";
            case 221:
                return "冰雷巫师";
            case 222:
                return "冰雷魔导师";
            case 230:
                return "牧师";
            case 231:
                return "祭祀";
            case 232:
                return "主教";
            case 300:
                return "弓箭手";
            case 310:
                return "猎人";
            case 311:
                return "射手";
            case 312:
                return "神射手";
            case 320:
                return "弩弓手";
            case 321:
                return "游侠";
            case 322:
                return "箭神";
            case 400:
                return "飞侠";
            case 410:
                return "刺客";
            case 411:
                return "无影人";
            case 412:
                return "隐士";
            case 420:
                return "侠客";
            case 421:
                return "独行客";
            case 422:
                return "侠盗";
            case 430:
                return "见习刀客";
            case 431:
                return "双刀客";
            case 432:
                return "双刀侠";
            case 433:
                return "血刀";
            case 434:
                return "暗影双刀";
            case 500:
                return "海盗(作废)";
            case 510:
                return "拳手(作废)";
            case 511:
                return "斗士(作废)";
            case 512:
                return "冲锋队长(作废)";
            case 520:
                return "火枪手(作废)";
            case 521:
                return "大副(作废)";
            case 522:
                return "船长(作废)";
            case 501:
                return "海盗炮手";
            case 530:
                return "火炮手";
            case 531:
                return "毁灭炮手";
            case 532:
                return "神炮王";
            case 508:
                return "龙的传人(1转)";
            case 570:
                return "龙的传人(2转)";
            case 571:
                return "龙的传人(3转)";
            case 572:
                return "龙的传人(4转)";
            case 509:
                return "海盗(新)";
            case 580:
                return "拳手(新)";
            case 581:
                return "斗士(新)";
            case 582:
                return "冲锋队长(新)";
            case 590:
                return "火枪手(新)";
            case 591:
                return "大副(新)";
            case 592:
                return "船长(新)";
            case 1100:
                return "魂骑士(1转)";
            case 1110:
                return "魂骑士(2转)";
            case 1111:
                return "魂骑士(3转)";
            case 1112:
                return "魂骑士(4转)";
            case 1200:
                return "炎术士(1转)";
            case 1210:
                return "炎术士(2转)";
            case 1211:
                return "炎术士(3转)";
            case 1212:
                return "炎术士(4转)";
            case 1300:
                return "风灵使者(1转)";
            case 1310:
                return "风灵使者(2转)";
            case 1311:
                return "风灵使者(3转)";
            case 1312:
                return "风灵使者(4转)";
            case 1400:
                return "夜行者(1转)";
            case 1410:
                return "夜行者(2转)";
            case 1411:
                return "夜行者(3转)";
            case 1412:
                return "夜行者(4转)";
            case 1500:
                return "奇袭者(1转)";
            case 1510:
                return "奇袭者(2转)";
            case 1511:
                return "奇袭者(3转)";
            case 1512:
                return "奇袭者(4转)";
            case 2100:
                return "战神(1转)";
            case 2110:
                return "战神(2转)";
            case 2111:
                return "战神(3转)";
            case 2112:
                return "战神(4转)";
            case 2200:
                return "龙神(1转)";
            case 2210:
                return "龙神(2转)";
            case 2211:
                return "龙神(3转)";
            case 2212:
                return "龙神(4转)";
            case 2213:
                return "龙神(5转)";
            case 2214:
                return "龙神(6转)";
            case 2215:
                return "龙神(7转)";
            case 2216:
                return "龙神(8转)";
            case 2217:
                return "龙神(9转)";
            case 2218:
                return "龙神(10转)";
            case 2002:
                return "双弩精灵";
            case 2300:
                return "双弩精灵(1转)";
            case 2310:
                return "双弩精灵(2转)";
            case 2311:
                return "双弩精灵(3转)";
            case 2312:
                return "双弩精灵(4转)";
            case 2003:
                return "幻影侠盗";
            case 2400:
                return "幻影侠盗(1转)";
            case 2410:
                return "幻影侠盗(2转)";
            case 2411:
                return "幻影侠盗(3转)";
            case 2412:
                return "幻影侠盗(4转)";
            case 3001:
                return "恶魔猎手";
            case 3100:
                return "恶魔猎手(1转)";
            case 3110:
                return "恶魔猎手(2转)";
            case 3111:
                return "恶魔猎手(3转)";
            case 3112:
                return "恶魔猎手(4转)";
            case 3200:
                return "幻灵斗师(1转)";
            case 3210:
                return "幻灵斗师(2转)";
            case 3211:
                return "幻灵斗师(3转)";
            case 3212:
                return "幻灵斗师(4转)";
            case 3300:
                return "弩豹游侠(1转)";
            case 3310:
                return "弩豹游侠(2转)";
            case 3311:
                return "弩豹游侠(3转)";
            case 3312:
                return "弩豹游侠(4转)";
            case 3500:
                return "机械师(1转)";
            case 3510:
                return "机械师(2转)";
            case 3511:
                return "机械师(3转)";
            case 3512:
                return "机械师(4转)";
            case 5000:
                return "无名少年";
            case 5100:
                return "米哈尔(1转)";
            case 5110:
                return "米哈尔(2转)";
            case 5111:
                return "米哈尔(3转)";
            case 5112:
                return "米哈尔(4转)";
                
                
    case 2004:
      return "夜光法师";
    case 2700:
      return "夜光法师(1转)";
    case 2710:
      return "夜光法师(2转)";
    case 2711:
      return "夜光法师(3转)";
    case 2712:
      return "夜光法师(4转)";
    case 6000:
      return "狂龙战士";
    case 6100:
      return "狂龙战士(1转)";
    case 6110:
      return "狂龙战士(2转)";
    case 6111:
      return "狂龙战士(3转)";
    case 6112:
      return "狂龙战士(4转)";
    case 6001:
      return "爆莉萌天使";
    case 6500:
      return "爆莉萌天使(1转)";
    case 6510:
      return "爆莉萌天使(2转)";
    case 6511:
      return "爆莉萌天使(3转)";
    case 6512:
      return "爆莉萌天使(4转)";
                
                
            case 900:
                return "管理员";
            case 910:
                return "超级管理员";
            case 800:
                return "管理者";
        }
        return null;
    }
}